# Generated by Django 4.2.7 on 2024-02-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_book_cover"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["Bid"], name="id_index"),
        ),
    ]
