# Generated by Django 4.2.7 on 2024-03-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_book_id_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(to="books.genre"),
        ),
    ]
