# Generated by Django 4.2.7 on 2024-06-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_genre_book_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
