# Generated by Django 4.2.7 on 2024-06-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_alter_book_cover_alter_book_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
