# Generated by Django 5.2.5 on 2025-08-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_slug_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title_searchable',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
