# Generated by Django 5.2.5 on 2025-08-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_remove_genre_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
