# Generated by Django 5.2.5 on 2025-08-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pretty_slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
