# Generated by Django 5.2.5 on 2025-08-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_book_pretty_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='id_index',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pretty_slug',
        ),
    ]
