name: CI / CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          # Initializes the database with 'root' user (matches your settings)
          POSTGRES_USER: root
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myanmar_bookreviews_test
        ports:
          - 5432:5432
        options: >-
          # CRITICAL FIX: The health check user must be 'root' to match POSTGRES_USER.
          --health-cmd "pg_isready -U root -d myanmar_bookreviews_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # FIX 1: The host is the service name 'postgres'
      DATABASE_URL: postgres://root:postgres@postgres:5432/myanmar_bookreviews_test
      SECRET_KEY: test-secret-key
      DEBUG: 'False'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (including dj-database-url)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # IMPORTANT: Your Django settings.py must use a package like dj-database-url 
          # to read the DATABASE_URL environment variable.

      - name: Wait for Postgres to be ready
        run: |
          # FIX 2: Check for readiness using the service name 'postgres'
          for i in {1..20}; do pg_isready -h postgres -p 5432 -U root && break || sleep 1; done

      - name: Run migrations
        run: |
          python manage.py migrate --noinput

      - name: Run tests
        run: |
          python manage.py test --verbosity=2

  # ----------------------------------------------------------------------
  # Continuous Delivery (CD) Job: Build and Push Docker Image
  # ----------------------------------------------------------------------

  build-and-publish:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    # Quality Gate: Only runs if the 'test' job succeeded
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        # Use GITHUB_TOKEN to authenticate with ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        # Builds the image using your Dockerfile and tags it
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          file: ./Dockerfile

  # ----------------------------------------------------------------------
  # Continuous Deployment (CD) Job: Deploy to EC2
  # ----------------------------------------------------------------------

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    # Only runs if the 'build-and-publish' job succeeded
    needs: build-and-publish
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Deployment Placeholder
        run: echo "Deployment process starts here. You would use SSH or AWS CLI actions to connect to your EC2 instance, pull the new Docker image, and restart the container."
        # **To make this deployment work, you will need to add:**
        # 1. AWS credentials as Secrets in your GitHub repo settings.
        # 2. A proper SSH or AWS CodeDeploy action here to interact with your EC2 instance.