name: CI / CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myanmar_bookreviews_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U root -d myanmar_bookreviews_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # Match the env var names your Django settings read
      DB_NAME: myanmar_bookreviews_test
      DB_USER: root
      DB_USER_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: '5432'
      SECRET_KEY: test-secret-key
      DEBUG: 'False'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Postgres to be ready
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client
          for i in {1..30}; do pg_isready -h postgres -p 5432 -U root && break || sleep 1; done

      - name: Run migrations
        run: python manage.py migrate --noinput

      - name: Run tests
        run: python manage.py test --verbosity=2

  build-and-publish:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

  deploy:
    name: Deploy (placeholder)
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deployment placeholder
        run: echo "Add deploy steps (SSH, kubectl, cloud CLI). Store production secrets in repo secrets."