name: CI / CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        # Use a recent, stable PostgreSQL image
        image: postgres:15
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: postgres
          # Database name for testing
          POSTGRES_DB: myanmar_bookreviews_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U root -d myanmar_bookreviews_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # FIX 1: The host must be the service name 'postgres', not 127.0.0.1
      DATABASE_URL: postgres://root:postgres@postgres:5432/myanmar_bookreviews_test
    steps:
      # ...
      - name: Wait for Postgres to be ready
        run: |
          # This is the last missing piece:
          for i in {1..20}; do pg_isready -h postgres -p 5432 -U root && break || sleep 1; done
      - name: Run migrations
        run: python manage.py migrate --noinput
