name: CI / CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    
    # 1. SETUP THE DATABASE SERVICE
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myanmar_bookreviews_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U root -d myanmar_bookreviews_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # 2. PROVIDE ENVIRONMENT VARIABLES (Matching your settings.py)
    env:
      # These 5 variables match what your settings.py is currently reading.
      DB_NAME: myanmar_bookreviews_test
      DB_USER: root
      DB_USER_PASSWORD: postgres
      DB_HOST: postgres # The service name for the internal network
      DB_PORT: '5432'
      # Other mandatory Django variables
      SECRET_KEY: test-secret-key
      DEBUG: 'False'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # IMPORTANT: Make sure your requirements.txt includes 'psycopg2-binary' and 'environs'
          pip install -r requirements.txt

      # NEW FIX: Install the necessary client tool (pg_isready) in a separate step
      - name: Install PostgreSQL Client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client
          
      # 3. SYNCHRONIZATION (The Handshake)
      - name: Wait for Postgres to be ready
        run: |
          # Use the installed tool to wait up to 30 seconds for the database service
          for i in {1..30}; do pg_isready -h postgres -p 5432 -U root && break || sleep 1; done

      # 4. CONNECTION TEST
      - name: Run migrations
        run: python manage.py migrate --noinput

      # 5. CODE QUALITY CHECK
      - name: Run tests
        run: python manage.py test --verbosity=2

  # ---
  # CD STAGES (Only run if 'test' passes)
  # ---
  build-and-publish:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Define a lowercase tag variable
      - name: Set lowercase repository variables
        id: vars
        run: |
          # The | tr '[:upper:]' '[:lower:]' command converts text to lowercase
          echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT
          echo "repo_lc=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          # CRITICAL FIX: Use the lowercase variables defined above
          tags: ghcr.io/${{ steps.vars.outputs.owner_lc }}/${{ steps.vars.outputs.repo_lc }}:latest
  deploy:
    name: Deploy (placeholder)
    runs-on: ubuntu-latest
    needs: build-and-publish # Quality Gate: requires 'build-and-publish' to pass
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deployment placeholder
        run: echo "Final step to SSH into server, pull the image, and restart the service."
